# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

##### main base config options #####

# Type of node currently running
node_type = "sentry"

# Turn on/off alerts for system events
alerting = true

# Type of Alert
alert_type = "commander"

# Port to listen on
port = 9393

# Beam Commander specific options
[commander]

# Turn on/off commander communication
enable = true

# Beam Commander Lambda function name
commander = "beam-commander"

# Beam Commander S3 Bucket
bucket = "beam-commander"

# Validator specific options
[validator]

# Set whether this Validator is primary or a stand by
primary = true

# Turn on/off automatic voting
voting = true

# Turn on/off steak automatic bonding
bonding = true

# Cosmos address
address = "abc1234basd"

# Sentry specific options
[sentry]

# Specify if sentry is private or public
public = true

# Check how many open connections
connections = true

# Turn on/off Defense if under DDoS attack
defense = true

# Gaiad Specifc Options
[gaiad]

# Turn on/off Gaiad configuration management
enable = true

# Gaiad directory
directory = "~/.gaiad"