# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

##### main base config options #####

# Type of node currently running
node_type = "sentry"

# Turn on/off alerts for system events
alerting = true

# Beam Commander specific options
[commander]

# Turn on/off commander communication
enable = true

# Beam Commander Lambda function name
commander = "beam-commander"

# Beam Commander S3 Bucket
bucket = "beam-commander"

# Validator specific options
[validator]

# Turn on/off automatic voting
voting = true

# Turn on/off steak automatic bonding
bonding = true

# Sentry specific options
[sentry]

# Turn on/off self replacement if under DDoS attack
suicide = true

# Gaiad Specifc Options
[gaiad]

# Turn on/off Gaiad configuration management
enable = true

# Gaiad directory
directory = "~/.gaiad"